// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwdPkw3P5qLezfwMhWOKh10C27INj7xvM',
    appId: '1:490671147785:web:42315c13fc1f8ad51de1d8',
    messagingSenderId: '490671147785',
    projectId: 'event-management-f70a2',
    authDomain: 'event-management-f70a2.firebaseapp.com',
    storageBucket: 'event-management-f70a2.appspot.com',
    measurementId: 'G-Y3J1CW74CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmxP4XgmeY-nq0wEKqHUtsQeCuT8lT8Z0',
    appId: '1:490671147785:android:42ff264614bd55281de1d8',
    messagingSenderId: '490671147785',
    projectId: 'event-management-f70a2',
    storageBucket: 'event-management-f70a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYDJoUMzf7-imIXPtthn9xx1B7Wvmzee8',
    appId: '1:490671147785:ios:e8ee6860f1fa87611de1d8',
    messagingSenderId: '490671147785',
    projectId: 'event-management-f70a2',
    storageBucket: 'event-management-f70a2.appspot.com',
    iosClientId: '490671147785-bc3b5f97nqsd1i9fj1rjq4emfino1era.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYDJoUMzf7-imIXPtthn9xx1B7Wvmzee8',
    appId: '1:490671147785:ios:e8ee6860f1fa87611de1d8',
    messagingSenderId: '490671147785',
    projectId: 'event-management-f70a2',
    storageBucket: 'event-management-f70a2.appspot.com',
    iosClientId: '490671147785-bc3b5f97nqsd1i9fj1rjq4emfino1era.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventManagement',
  );
}
